import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { UserInfoStoreProvider } from "@/providers/UserInfoProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../static/font/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body
        className={`${pretendard.className} w-screen h-screen bg-slate-100`}
      >
        <UserInfoStoreProvider>{children}</UserInfoStoreProvider>
      </body>
    </html>
  );
}
